
## Numpy

In [12]:
# how  to import 
import numpy as np


#  why to use numpy over lists 

#  - lists are excellent for genral purpose.  
# but numpy provides improve speed , reduce memory consumption for large data.


# how to initialize an array using np 
arr1 = np.array([1,2,3,4,6])
print("Array : ",arr1)



# you can access elements using indexing 
print("\nele at index 2 : ",arr1[2])  # positive ordering from left to right goes from 0  to size-1;
print("ele at last index : ",arr1[-1]) # negative ordering to access elements from right to left from -1 to -size-1;



# slicing in array for access specific window elements;

# eg :  accessing  from 2 element to 4 th element
print("\nSlice 2 to 4: ",arr1[1:4])


Array :  [1 2 3 4 6]

ele at index 2 :  3
ele at last index :  6

Slice 2 to 4:  [2 3 4]


## Attributes of Array 

In [38]:
array1 = np.array([1,2,3,4,5,6,7,8])
array_2d = np.array([[1,2,3,4],[5,6,7,8]])

# to get dimensions 
print("Dimensions :",array1.ndim)
print("Dimensions :",array_2d.ndim)



# to get number of rows and columns
print("\nShape of 1d array : ",array1.shape)
print("Shape of 2d array : ",array_2d.shape)


# to get size of array
print("\nSize of array : ",array1.size, " ", array_2d.size)

# to get type of elements

print("\nType of array elments : ",array1.dtype)

Dimensions : 1
Dimensions : 2

Shape of 1d array :  (8,)
Shape of 2d array :  (2, 4)

Size of array :  8   8

Type of array elments :  int32


## Creation of arrays

In [42]:
# arrays of zeroes

# constructing 1d array
print(np.zeros(10))

# constructing 2d arrays
print("\n",np.zeros((2,4)))



# arrays of ones

#construct 1d array
print("\n",np.ones(4))

# construct 2d array
print("\n",np.ones((3,4)))



# create elements for range
print("\n",np.arange(6))

# or you can alter the range
print("\n",np.arange(2,10,3))


# if you have fixed range and wants numerb of elements from that range 
# suppose i want 10 elments between 1 and 2.
print('\n',np.linspace(1,2,10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [1. 1. 1. 1.]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [0 1 2 3 4 5]

 [2 5 8]

 [1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


## Adding , Removing , Soting and other operations

In [61]:
# to add two different arrays
arr1 = np.array([1,2,3,4,5])
print("arr1  : ",arr1, "\n");

arr2 = np.array([2,3,7,5,9])
print("arr2  : ",arr2,"\n");

print("Concatenation : ",np.concatenate((arr1,arr2),axis = 0) );


# we can also reshape array : 
temp = np.arange(12)
new_array = temp.reshape(3,4)
print("\nReshaping array : \n",new_array)

arr1  :  [1 2 3 4 5] 

arr2  :  [2 3 7 5 9] 

Concatenation :  [1 2 3 4 5 2 3 7 5 9]

Reshaping array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [72]:
arr = np.arange(20)

# perform operations like

print(arr[arr > 10])

print(arr[arr % 2 == 0])

print(arr[arr % 3 == 0])

print(arr[(arr > 3) & (arr < 10)])

# check conditions

print(arr & 1)

[11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18]
[4 5 6 7 8 9]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


## Stacking Vertically and Horizontally

In [86]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

# stacking vertically
print("Stacking Vertically : \n",np.vstack((a,b)));

# stacking horizontally
print("stacking Horizontally : \n",np.hstack((a,b)));

# adding multiple arrays by simple operators

print("\nAddition :",a + b)
print("Subtraction :",a-b)
print("Multiplication",a*b)
print("scalar operation",a/2)


print("\n",a/b)

Stacking Vertically : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
stacking Horizontally : 
 [ 1  2  3  4  5  6  7  8  9 10]

Addition : [ 7  9 11 13 15]
Subtraction : [-5 -5 -5 -5 -5]
Multiplication [ 6 14 24 36 50]
scalar operation [0.5 1.  1.5 2.  2.5]

 [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## Most useful functions

In [101]:
temp = np.arange(25).reshape((5,5))

print(temp)

print("\nMax ele :",np.max(temp))
print("Min ele :",np.min(temp))
print("Sum : ",np.sum(temp))
print("Get uniques : ",np.unique(temp))


print("\nTranspose :",temp.transpose())
print("\n Reverse : ",np.flip(temp))
print("\n Squaring :",np.square(temp))
w

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Max ele : 24
Min ele : 0
Sum :  300
Get uniques :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

Transpose : [[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]

 Reverse :  [[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]

 Squaring : [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]
